# Generated by Django 5.2.8 on 2025-11-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_brand_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
