# Generated by Django 5.2.8 on 2025-11-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_delete_brand_delete_image_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='admin', max_length=10),
        ),
    ]
