# Generated by Django 5.2.8 on 2025-11-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isBlock',
            field=models.BooleanField(default=False),
        ),
    ]
