# Generated by Django 5.2.8 on 2025-12-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Card'), ('razorpay', 'Razorpay')], max_length=20, null=True),
        ),
    ]
